const $=id=>document.getElementById(id);let state={user:null,projects:[],current:null};
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function show(id){["loginView","registerView","dashboardView","adminView"].forEach(x=>$(x).classList.add("hidden"));$(id).classList.remove("hidden")}
function msg(el,text,type=""){el.innerHTML=text?`<div class="msg ${type}">${escapeHtml(text)}</div>`:""}
function token(){return localStorage.getItem("deploy_token")||""}
async function api(action,data={}){if(!API_URL||API_URL.includes("PASTE_"))throw Error("API_URL belum diatur di config.js");const p=new URLSearchParams({action,...data});const r=await fetch(API_URL+"?"+p);const j=await r.json();if(!j.ok)throw Error(j.error||"Terjadi kesalahan");return j}
async function apiAuth(action,data={}){return api(action,{...data,token:token()})}
$("showRegister").onclick=()=>show("registerView");$("showLogin").onclick=()=>show("loginView");
function logout(){localStorage.removeItem("deploy_token");state={user:null,projects:[]};show("loginView")}
$("logoutBtn").onclick=logout;$("adminLogout").onclick=logout;$("mobileLogout").onclick=logout;
$("loginForm").onsubmit=async e=>{e.preventDefault();msg($("loginMsg"),"Memeriksa akun...");try{let r=await api("login",{identifier:$("loginId").value,password:$("loginPassword").value});localStorage.setItem("deploy_token",r.token);state.user=r.user;await loadDashboard()}catch(x){msg($("loginMsg"),x.message,"error")}}
$("registerForm").onsubmit=async e=>{e.preventDefault();msg($("registerMsg"),"Mengirim pendaftaran...");try{await api("register",{name:$("regName").value,username:$("regUsername").value,email:$("regEmail").value,password:$("regPassword").value});msg($("registerMsg"),"Pendaftaran berhasil. Tunggu persetujuan admin.","success");e.target.reset()}catch(x){msg($("registerMsg"),x.message,"error")}}
async function loadDashboard(){try{let r=await apiAuth("me");state.user=r.user;state.projects=r.projects;renderDashboard();show("dashboardView")}catch(x){localStorage.removeItem("deploy_token");show("loginView");msg($("loginMsg"),x.message,"error")}}
function nextSlot(){for(let i=1;i<=5;i++)if(!state.projects.some(x=>Number(x.slot)===i))return i;return 1}
function renderDashboard(){let u=state.user;$("hello")&&($("hello").textContent=`Halo, ${u.name}`);$("sideName").textContent=u.name;$("sideRole").textContent=u.role;$("avatar").textContent=(u.name||"U")[0].toUpperCase();$("count").textContent=state.projects.length;$("progress").style.width=(state.projects.length/5*100)+"%";let deployed=state.projects.filter(x=>x.deployId&&x.status==="DEPLOYED").length;$("deployedCount").textContent=deployed;let latest=state.projects.map(x=>new Date(x.updatedAt)).filter(x=>!isNaN(x)).sort((a,b)=>b-a)[0];$("lastUpdated").textContent=latest?latest.toLocaleDateString("id-ID",{day:"numeric",month:"short"}):"—";$("adminBtn").style.display=u.role==="ADMIN"?"block":"none";
let h="";for(let i=1;i<=5;i++){let p=state.projects.find(x=>Number(x.slot)===i);if(p)h+=`<div class="project-card"><span class="project-num">KARYA ${i}</span><div class="project-title">${escapeHtml(p.title||"Tanpa judul")}</div><span class="status ${p.status==="DEPLOYED"?"live":"draft"}">${p.status==="DEPLOYED"?"● DEPLOYED":"DRAFT"}</span><div class="project-date">${p.updatedAt?new Date(p.updatedAt).toLocaleDateString("id-ID",{day:"numeric",month:"long",year:"numeric"}):"Belum diperbarui"}</div><div class="project-actions"><button class="edit" onclick="editProject(${i})">Edit</button><button class="preview" onclick="previewProject(${i})">Preview</button>${p.deployId?`<button class="preview" onclick="copyDeploy(${i})">⧉</button>`:""}</div></div>`;else h+=`<div class="project-card empty"><div class="plus-circle">＋</div><b>Karya ${i}</b><small>Slot masih kosong</small><button class="edit" style="margin-top:12px;border:0;background:#eeeaff;color:#5b48c3;padding:8px 12px;border-radius:8px;font-weight:700" onclick="newProject(${i})">Buat karya</button></div>`}$("projects").innerHTML=h}
window.newProject=slot=>openEditor({slot,title:"",html:"",deployId:""});window.editProject=slot=>openEditor(state.projects.find(x=>Number(x.slot)===slot)||{slot,title:"",html:"",deployId:""});window.previewProject=slot=>openEditor(state.projects.find(x=>Number(x.slot)===slot)||{slot,title:"",html:"",deployId:""});
function openEditor(p){state.current=p;$("editorTitle").textContent=`Karya ${p.slot}`;$("projectTitle").value=p.title||"";$("htmlCode").value=p.html||"";$("previewFrame").srcdoc=p.html||"";$("deployResult").innerHTML="";$("copyBtn").classList.toggle("hidden",!p.deployId);updateChars();$("editorModal").classList.remove("hidden")}
$("closeEditor").onclick=()=>$("editorModal").classList.add("hidden");$("htmlCode").oninput=updateChars;function updateChars(){$("charCount").textContent=$("htmlCode").value.length.toLocaleString("id-ID")+" karakter"}
$("previewBtn").onclick=()=>{$("previewFrame").srcdoc=$("htmlCode").value}
$("saveBtn").onclick=async()=>{try{let p=state.current,r=await apiAuth("saveProject",{slot:p.slot,title:$("projectTitle").value,html:$("htmlCode").value});replaceProject(r.project);$("deployResult").innerHTML='<div class="msg success">Draft berhasil disimpan.</div>';state.current=r.project;$("copyBtn").classList.toggle("hidden",!r.project.deployId)}catch(x){msg($("deployResult"),x.message,"error")}}
$("deployBtn").onclick=async()=>{try{let p=state.current,r=await apiAuth("deploy",{slot:p.slot,title:$("projectTitle").value,html:$("htmlCode").value});replaceProject(r.project);state.current=r.project;$("copyBtn").classList.remove("hidden");$("deployResult").innerHTML=`<div class="msg success">Live: <a href="${escapeHtml(r.url)}" target="_blank">Buka hasil deploy ↗</a></div>`}catch(x){msg($("deployResult"),x.message,"error")}}
function replaceProject(p){state.projects=state.projects.filter(x=>Number(x.slot)!==Number(p.slot));state.projects.push(p);renderDashboard()}
window.copyDeploy=async slot=>{let p=state.projects.find(x=>Number(x.slot)===slot);if(!p?.deployId)return;let url=deployUrl(p.deployId);try{await navigator.clipboard.writeText(url);alert("Link deploy berhasil disalin")}catch(e){prompt("Salin link:",url)}}
function deployUrl(id){return window.location.origin+window.location.pathname+"?p="+encodeURIComponent(id)}
$("copyBtn").onclick=()=>{let p=state.current;if(p?.deployId)navigator.clipboard.writeText(deployUrl(p.deployId)).then(()=>$("deployResult").innerHTML='<div class="msg success">Link disalin.</div>')}
$("adminBtn").onclick=loadAdmin;$("backDash").onclick=()=>show("dashboardView");
async function loadAdmin(){try{let r=await apiAuth("adminUsers"),pending=r.users.filter(x=>x.status==="PENDING");$("pendingCount").textContent=pending.length;$("userCount").textContent=r.users.length;$("pendingUsers").innerHTML=pending.map(x=>`<div class="user-row"><div><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.username)} · ${escapeHtml(x.email)}</small></div><button onclick="approveUser('${x.id}')">✓ ACC</button></div>`).join("")||'<div style="padding:22px;color:#999;font-size:12px">Tidak ada pendaftaran yang menunggu.</div>';$("allUsers").innerHTML='<div class="table-wrap"><table class="table"><tr><th>USERNAME</th><th>NAMA</th><th>STATUS</th><th>ROLE</th></tr>'+r.users.map(x=>`<tr><td>${escapeHtml(x.username)}</td><td>${escapeHtml(x.name)}</td><td>${escapeHtml(x.status)}</td><td>${escapeHtml(x.role)}</td></tr>`).join("")+"</table></div>";show("adminView")}catch(x){msg($("adminMsg"),x.message,"error")}}
window.approveUser=async id=>{try{await apiAuth("approveUser",{userId:id});loadAdmin()}catch(x){msg($("adminMsg"),x.message,"error")}}
(async()=>{let publicId=new URLSearchParams(location.search).get("p");if(publicId){try{let r=await api("public",{deployId:publicId});document.body.innerHTML=r.html;document.title=r.title||"HTML Deploy";return}catch(e){document.body.innerHTML="<div style='font-family:Arial;padding:50px;text-align:center'><h2>Karya tidak ditemukan</h2><p>Link deploy mungkin sudah tidak tersedia.</p></div>";return}}if(token())loadDashboard();else show("loginView")})();